kind = "DojoModel"
class_hash = "0x70b89f08ddc95bbc74debac577a96d9a5f2fe0f119f97fe8f6875a0fcafb787"
original_class_hash = "0x70b89f08ddc95bbc74debac577a96d9a5f2fe0f119f97fe8f6875a0fcafb787"
abi = "manifests/dev/abis/base/models/gladiethers_models_position_position.json"
name = "gladiethers::models::position::position"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "vec"
type = "Vec2"
key = false
